### PR TITLE
[민준혁] tcp/ip의 기본개념

### PR DESCRIPTION
**Pull request by HIITMEMARIO**
https://velog.io/@alswnsgur119/TCPIP

### CODE REVIEW

**Review by Minseok1228 — APPROVED** [review]
Good

**Review by Yeomhyewon — APPROVED** [review]
👍

**Review by scseong — APPROVED** [review]
tcp/ip 추상화한 글인데 공유해보아요
https://yozm.wishket.com/magazine/detail/1906/

**Review by h0ngwon — APPROVED** [review]
LGTM

**Comment by heeneeee** [comment]
잘봤습니다

**Review by heeneeee — APPROVED** [review]

**Pull request merged**
